version: 2

jobs:
  build:
    branches:
      only:
        - master
        
    machine:
      image: ubuntu-1604:201903-01
      
    steps:
      - checkout
         
      - run:
          name: Installing GCC
          command: 'sudo apt-get -y update && sudo apt-get -y install software-properties-common && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get -y update && sudo apt-get -y install -y gcc g++ libtool autoconf automake cmake gcc-9 g++-9'
         
      - run:
          name: Check GCC version
          command: 'export CC=gcc-9 && export CXX=g++-9 && $CXX --version'
          
      - run:
          name: Installing CMake
          command: 'sudo apt purge cmake && sudo wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4.tar.gz && tar -zxvf cmake-3.13.4.tar.gz && cd cmake-3.13.4 && sudo ./bootstrap && sudo make && sudo make install'
         
      - run:
          name: Check CMake version
          command: 'cmake --version'

      - run:
          name: Installing Ninja
          command: 'sudo apt-get -y update && sudo apt-get -y install ninja-build'

      - run:
          name: Build project
          command: 'cd /home/circleci/project && sudo mkdir Build && cd Build && sudo cmake -G Ninja -D CMAKE_CXX_COMPILER=g++-9 .. && sudo ninja'
          
      - store_artifacts:
          path: /home/circleci/project/Build
